version: '3.7'
services:
  backend:
    image: antoniopapa1991/admin-backend
    environment:
      DB_HOST: db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin21
      MYSQL_USER: root21
      MYSQL_PASSWORD: root21
      MYSQL_ROOT_PASSWORD: root21
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - app
networks:
  app: